# Generated by Django 5.1.7 on 2025-04-14 05:32

import othello.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Game",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("turn", models.CharField(default="black's turn", max_length=15)),
                ("board", models.JSONField(default=othello.models.default_settings)),
            ],
        ),
    ]
