# Generated by Django 5.2 on 2025-04-17 09:29

import django.db.models.deletion
import othello.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuthenticatedLocalMatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("black_player", models.CharField(max_length=255)),
                ("white_player", models.CharField(max_length=255)),
                ("turn", models.CharField(default="black's turn", max_length=15)),
                ("board", models.JSONField(default=othello.models.default_settings)),
                ("result", models.CharField(default="対局中", max_length=15)),
                (
                    "authenticated_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
