# Generated by Django 5.1.7 on 2025-03-14 06:38

from django.db import migrations

def create_initial_data(apps, schema_editor):
    # モデルを取得
    Game = apps.get_model('othello', 'Game')  # 'yourapp' と 'Book' は自分のモデル名に変更

    #盤面の初期状態を定義
    initial_board=[]
    for i in range(8):
        initial_board.append(['empty']*8)
    initial_board[3][3] = 'black'
    initial_board[4][4] = 'black'
    initial_board[3][4] = 'white'
    initial_board[4][3] = 'white'
    
    #ゲームの初期状態を定義
    Game.objects.create(turn="black\'s turn", board=initial_board)

class Migration(migrations.Migration):

    dependencies = [
        ('othello', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_initial_data),
    ]
