# Generated by Django 5.1.7 on 2025-03-15 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('othello', '0002_add_initial_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='turn',
            field=models.CharField(max_length=10),
        ),
    ]
