# Generated by Django 5.1.7 on 2025-03-15 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('othello', '0003_alter_game_turn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='turn',
            field=models.CharField(max_length=15),
        ),
    ]
