@startuml screen_header_flow
skinparam defaultFontName "Noto Sans CJK JP"
hide empty description


title オセロアプリヘッダー 画面遷移図

' 状態の定義
state 任意の画面
state ログイン中の任意の画面

[*] --> ホーム画面
state ホーム画面 {
    state ログイン前
    state ログイン後
    ログイン後 --> ログイン前 : ログアウト後
}

state アカウント機能 {
    state ログイン画面
    state パスワード変更
    state ユーザー登録
    state パスワード変更確認
    パスワード変更 --> パスワード変更確認
    ユーザー登録 --> ログイン画面 : ユーザー登録後
}



'　ホーム画面とアカウント機能の遷移
ログイン前 --> ログイン画面
ログイン画面 --> ログイン後 
ログイン前 --> ユーザー登録



' ヘッダー
任意の画面 --> ログイン前 : *未ログイン時
任意の画面 --> ログイン後 : *ログイン時
ログイン中の任意の画面 --> ログイン前 : ログアウト後
ログイン中の任意の画面 --> パスワード変更

note right of 任意の画面 
    ヘッダーの左上のアプリ名をクリック
    どの画面からでもホーム画面に戻れる
    ・未ログイン時 → ホーム（ログイン前）
    ・ログイン時 → ホーム（ログイン後）
endnote 
note right of ログイン中の任意の画面
    ヘッダーの右上のアカウント名をクリック
    ログアウト・パスワード変更を選択できる
endnote 


@enduml
