@startuml screen_flow
skinparam defaultFontName "Noto Sans CJK JP"
hide empty description


title オセロアプリ 画面遷移図

[*] --> ホーム画面
state ホーム画面 {
    state ログイン前
    state ログイン後
    ログイン前 --> ログイン後 : ログインする
    ログイン後 --> ログイン前 : ログアウトする
}



state ゲーム管理 {
    state 新規ゲーム作成
    state ローカル対戦
    state 対局履歴確認
    state ゲーム削除
    対局履歴確認 --> ローカル対戦 : 過去の対局を選択    
    新規ゲーム作成 --> ローカル対戦 : ゲーム開始
    対局履歴確認 --> ゲーム削除 : 対局削除
    ゲーム削除 --> 対局履歴確認 :　ゲーム削除後
}

state ゲームプレイ {
    [*] --> 駒を打つ
    [*] --> パスする
    [*] --> 終局処理
    終局処理 --> [*] : ゲーム終了
    state 駒を打つ
    state パスする
    state 終局処理
}

' ホーム画面とゲーム管理の遷移
ログイン後 --> 新規ゲーム作成
ログイン後 --> 対局履歴確認



' ゲーム管理とゲームプレイの遷移
ローカル対戦 --> ゲームプレイ : 対局開始






@enduml
