@startuml screen flow
skinparam defaultFontName "Noto Sans CJK JP"

title オセロアプリ 画面遷移図

state ホーム {
  [*] --> ホーム画面
  ホーム画面 --> ログイン画面 
  ログイン画面 --> ホーム画面 : 成功
  ログイン画面 --> ログイン画面 : 失敗
  ホーム画面 --> ログアウト画面 : ログアウト
  ログアウト画面 --> ホーム画面
}

state ローカル対戦 {
    ホーム画面 --> ローカル対戦画面
}

state リモート対戦 {
  ホーム画面 --> リモート対戦待合: 要ログイン
  リモート対戦待合 --> リモート対戦画面 : 要対戦処理
  
}

@enduml
