@startuml game_management_usecase
skinparam defaultFontName "Noto Sans CJK JP"
left to right direction

actor ゲストユーザー as guestuser

actor ログインユーザー as loggedInUser

actor 黒のプレイヤー as blackPlayer
actor 白のプレイヤー as whitePlayer

rectangle "オセロアプリ" {
  package "ゲーム管理" {
    (新しい対局を始める) as createNewGame
    (対局履歴を閲覧する) as GameHistory
    (対局を削除する) as deleteGame
    (対局を再開する) as restartGame

    (黒、白のプレイヤー名を\n入力する) as PlayerName
    createNewGame ..> PlayerName : <<include>>
}
  package "ゲームプレイ" {
    (ローカル対戦をプレイする) as playLocalGame
    (駒を打つ) as placePiece
    (パスをする) as passTurn
    (勝敗判定を行う) as endGame
    playLocalGame ..> placePiece : <<include>>
    playLocalGame ..> passTurn : <<include>>
    playLocalGame ..> endGame : <<include>>
  }
}

guestuser --> createNewGame

loggedInUser --> createNewGame
loggedInUser --> GameHistory
loggedInUser --> deleteGame
loggedInUser --> restartGame

blackPlayer --> playLocalGame
whitePlayer --> playLocalGame

note bottom of blackPlayer
黒、白のプレイヤーの一方は
ログインユーザーないしゲストユーザー、
もう一方は同じ場にいる他の人を想定
end note

@enduml