@startuml usecase
skinparam defaultFontName "Noto Sans CJK JP"
actor ログインユーザー
actor ゲスト
actor ユーザー

ゲスト --|> ユーザー
ログインユーザー --|> ユーザー

package "オセロアプリ " {
ゲスト --> (ユーザー登録)
ゲスト --> (ログイン)
ログインユーザー --> (ログアウト)
ユーザー --> (パスワード変更)
ログインユーザー --> (リモート対戦)
ユーザー --> (ローカル対戦)
ログインユーザー --> (リモート対戦に至るまでの処理)
}
@enduml